### ISSUE TITLE
Missing bitcoinjs fork attribution

### ISSUE THREAD

**Issue by dcousens** [ArkEcosystem/ark-js#20]
Hi!

Could you please add

> Copyright (c) 2011-2016 bitcoinjs-lib contributors

to your LICENSE?  As this appears to be a bitcoinjs-lib fork.
Cheers

**Comment by fix** [comment]
Yes i reused some parts of btincoinjs-lib. PR now merged. Thanks for pointing out

**Comment by dcousens** [comment]
Thanks @fix!
Hope I didn't give off a negative vibe :+1:

**Comment by fix** [comment]
not even, quite positive vibe seeing people from bitcoin hanging there :)
