### ISSUE TITLE
Possible typo in crypto test

### ISSUE THREAD

**Issue by iursevla** [ArkEcosystem/ark-js#22]
Sorry, if typos are not issues. Anyway saw this possible typo at [test/crypto](https://github.com/ArkEcosystem/ark-js/blob/master/test/crypto/index.js#L60)

>  it("should return Buffer of transaction with second signature and buffer **most** be 266 length", function () ...

**most** -> must

**Comment by alexbarnsley** [comment]
I'd say it does @iursevla, need to report it somewhere. I've corrected in a PR for you. Nice spot if I may say so myself xD
