### ISSUE TITLE
Error createTransaction with Webpack

### ISSUE THREAD

**Issue by willdn** [ArkEcosystem/ark-js#35]
I get an error while creating a transaction with the createTransaction() method. This error only appear when using the built Webpack app, everything works fine in development.
![error](https://user-images.githubusercontent.com/32334614/32416623-787a0862-c24c-11e7-81cc-4f4a097fa66e.png)

### Reproduce
Clone https://github.com/willdn/AWW and `npm install && npm run build` (no error when using `npm run dev`) or go to https://willdn.github.io/AWW/ . Open a wallet and send a transaction. The call to createTransaction() is made at https://github.com/willdn/AWW/blob/master/src/components/Send.vue#L140

**Comment by fix** [comment]
i think you should put null for second passphrase instead of `''`

**Comment by willdn** [comment]
I get the same error

**Comment by willdn** [comment]
Fixed, added this in `webpack.conf`

```
  node: {
    fs: 'empty'
  }
```

**Comment by faustbrian** [comment]
Will close this as we are working on v2.
