### ISSUE TITLE
getKeys only returns publicKey

### ISSUE THREAD

**Issue by n4ru** [ArkEcosystem/ark-js#38]
Running `ark.crypto.getKeys("twelve words here");` is only returning a publicKey inside the ECPair object, with the privateKey being blank.

**Comment by willdn** [comment]
That's the default behaviour, see https://github.com/ArkEcosystem/ark-js/blob/95b591c4641ab12869890889c9e3cbbcbe457166/lib/v2/transactions/crypto.js#L285 

I believe the documentation should specify this, at the moment the response method does not match what is specified in the documentation.

You can access the private key like this : 
`keys.d.toBuffer().toString('hex')`
