### ISSUE TITLE
RunKit not working

### ISSUE THREAD

**Issue by liamkeily** [ArkEcosystem/ark-js#42]
https://npm.runkit.com/arkjs

Error: Cannot find module 'create-hash'

**Comment by acidspud** [comment]
Added:

`var createHash = require("create-hash")
var safeBuffer = require("safe-buffer")`

On top of:

`var arkjs = require("arkjs");`

And it seems to be working try it.

**Comment by faustbrian** [comment]
Will close this as we are working on v2.
