### ISSUE TITLE
Got this issue while testing

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-js#5]
https://github.com/bitpay/bitcore-lib/issues/47

Maybe wise to pad the private key when generated something like:

`this.d=new BigInteger(this.d.toBuffer({size:32}));`

But the issue can be that BigInteger ignore leading 0...

Maybe better to fix here:

https://github.com/ArkEcosystem/ark-js/blob/master/lib/ecpair.js#L137

`this.d.toBuffer({size:32})`

**Comment by fix** [comment]
cases in hand to be added to tests:

```
passhprase iwrj4zyz1cghtz7zxgvi 
private key 2535b7a87019a0461f50a96747e9a0fd5ac7eb69e50fd7ca4d599d77634b71
length 31
```

```
passhprase ghpuw96rot6466mq85mi -  
private key d5a63ba2cebcbd0e1d5de0b01d9f34a2f24b230583a3f83023c4b67f2b171e
length 31
```

private key obtained by:
keypair.d.toBuffer().toString("hex")

**Comment by fix** [comment]
ok need to add test

**Comment by fix** [comment]
don't have time to include it in ark-js, but working on ark-node.
```
it('using fake passphrases, could raise error with wrong private key', function (done) {
			var transaction, p1, p2;
			p1="iwrj4zyz1cghtz7zxgvi";
			p2="ghpuw96rot6466mq85mi";

			try{
				var transaction = node.ark.transaction.createTransaction('AacRfTLtxAkR3Mind1XdPCddj1uDkHtwzD', 1, null, p1, p2);
			}
			catch(error){
				node.expect(true).to.be.not.ok;
			}
			done();
		});

```

**Comment by Doweig** [comment]
Commit https://github.com/ArkEcosystem/ark-js/commit/0bd054ec3ec762ee6361bcd2fed65e893dee7853 was pushed to master, I think you meant to push to dev

**Comment by fix** [comment]
yes :)
