### ISSUE TITLE
error in address generation

### ISSUE THREAD

**Issue by fix** [ArkEcosystem/ark-js#7]
this
https://github.com/ArkEcosystem/ark-js/blob/master/lib/ecpair.js#L117
gives a different result from 
https://github.com/ArkEcosystem/ark-js/blob/master/lib/transactions/crypto.js#L262

because the hash function is different

**Comment by Doweig** [comment]
Make the legacy getAddress() function use ECPair internally?

**Comment by fix** [comment]
mmm one more hash on ECPair.getAddress() i would do the inverse:
- reuse the logic from crypto.getAdress() inside  ECPair.getAddress()
- make crypto.getAdress() calling  ECPair.getAddress()

This will be different from bitcoin though (breaking bitcoin test)

**Comment by Doweig** [comment]
Did change the crypto code to use ECPair internally because it would be too heavy to implement. There's a test that checks that both schemes generate same addresses instead
