### ISSUE TITLE
Cannot create Devnet||testnet wallet address. And I cannot find devnet faucet.

### ISSUE THREAD

**Issue by fsanano** [ArkEcosystem/ark-js#81]
Hi, I try create test wallet:
```
import ark from 'ark';

const network = ark.networks.testnet;
ark.crypto.getKeys(seed, network);
```

But every time generate wallet address started with 'A'.

And if I can create dev wallet. Where I can get devnet coins ?

**Comment by wownmedia** [comment]
you need to set the correct network version in arkjs first, after that it
will generate devnet ardresses

**Comment by fsanano** [comment]
@wownmedia Thank you !
I changed my script to: 
```
import ark from 'ark';

ark.crypto.setNetworkVersion(0x52); // for testnet, for ark (mainet) 0x17

const network = ark.networks.testnet;
ark.crypto.getKeys(seed, network);
```

But In my ArkClient for desktop when I create devnet wallet, wallet started with 'D'.
Testnet and wallets started with 'a' deprecated?

**Comment by wownmedia** [comment]
by head I believe devnet version is 30 and mainnet is 23, so please
confirm. Address should be starting with D.

**Comment by fsanano** [comment]
I was guided by this [file](https://github.com/ArkEcosystem/ark-js/blob/master/lib/networks.js), so I choose 0x52. Anyway thank you!
